import { iconsType } from './index';
export const icons: iconsType[] = [
  'Add',
  'AngleLeft',
  'BookOpen',
  'BullHorn',
  'CaretRight',
  'Document',
  'Ellipsis',
  'Eye',
  'FileArrowDown',
  'Home',
  'Info',
  'PenToSquare',
  'ShareNodes',
  'User',
  'Video',
  'CircleQuestion',
  'Star',
  'Tag',
  'Bars',
  'AngleDown',
];
