name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  CI: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: install dependecies
        run: npm install --no-audit --no-fund --no-optional
      - name: lint
        run: npm run lint
      - name: npm run test
        run: npm run test
